'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const icons={home:'M3 11 12 3l9 8M5 10v10h5v-6h4v6h5V10',case:'M3 8h18v12H3zM8 8V4h8v4M3 12h18M10 12v3h4v-3',upgrade:'m4 12 8-8 8 8M8 12l4-4 4 4M12 8v13',battle:'m4 3 15 16M3 4l2 5 4-4zM15 18l3-3M3 21l5-5M20 3 5 18M21 4l-2 5-4-4zM9 18l-3-3M21 21l-5-5',contract:'M8 3h10v16H6V7M8 3v4H4v14h12M10 10h5M10 14h5',shop:'M2 3h3l3 12h11l3-9H6M9 19h.1M18 19h.1',tasks:'M8 4H5v17h14V4h-3M8 2h8v5H8zM8 13l3 3 5-6',refs:'M9 10a3 3 0 1 0 0-6 3 3 0 0 0 0 6M2 21v-4c0-6 14-6 14 0v4M17 4c4 0 4 6 0 6M18 14c4 0 4 4 4 7',top:'M7 3h10v7c0 6-10 6-10 0zM7 5H3v5c0 3 4 3 4 3M17 5h4v5c0 3-4 3-4 3M12 15v5M7 21h10',support:'M3 13v-2a9 9 0 0 1 18 0v2M3 11h3v7H3zM18 11h3v7h-3zM18 18c0 4-6 4-6 4',gift:'M3 8h18v5H3zM5 13v8h14v-8M12 8v13M12 8c-9 0-6-9-2-5l2 5c9 0 6-9 2-5z',crown:'m2 6 5 5 5-8 5 8 5-5-3 14H5zM6 17h12',gem:'m4 3-3 6 11 12L23 9l-3-6zM1 9h22M8 3 6 9l6 12 6-12-2-6',bell:'M5 17h14l-2-3V9C17 2 7 2 7 9v5zM10 21h4',copy:'M9 3h11v15H9zM5 7H3v15h11v-2',check:'m4 12 5 5L20 6',play:'m8 4 12 8-12 8z',event:'m12 2 3 7 7 3-7 3-3 7-3-7-7-3 7-3z',coin:'M12 2a10 10 0 1 0 0 20 10 10 0 0 0 0-20M15 7H9v5h6v5H9M12 5v14',send:'m2 10 20-8-6 20-4-8-10-4zM12 14l10-12',music:'M9 18V5l11-2v13M9 17c-8-4-8 7 0 3M20 15c-8-4-8 7 0 3',chat:'M3 4h18v14H8l-5 4zM7 9h10M7 13h7'};
function icon(n){return `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${icons[n]||icons.case}"/></svg>`}
const coin='<i class="coin" aria-hidden="true">$</i>';
const cases=[['STARTER','#55df8b',0],['ELITE','#45a2ff',49],['NIGHTMARE','#d34dff',149],['LEGEND','#e7b34b',299],['DRAGON','#ff4b5d',499],['INFINITY','#91bdff',999]];
const skins=[['AK-47','Redline','#ff596b',4321],['AWP','Asiimov','#ff714f',12900],['M4A1-S','Printstream','#9b77ff',8420],['★ Karambit','Doppler','#d25cff',215000],['Glock-18','Fade','#ffb34e',38600],['AK-47','Gold Arabesque','#e3ba42',182400],['M4A4','Howl','#ff4b58',498000],['AUG','Chameleon','#78a9ff',5240]];
const defaults={version:3,coins:37,gems:12450,inv:[],opens:0,wins:0,ads:0,battles:[],claims:[],daily:0,event:false,name:'SANEK',tickets:[],refClicks:0,language:'RU'};
let state;try{state={...defaults,...JSON.parse(localStorage.getItem('caseclash.v3')||'null')};if(!Array.isArray(state.inv))state.inv=[];if(!Number.isFinite(state.coins)||state.coins<0)state.coins=37;}catch{state={...defaults};}
let busy=false,slide=0,lastFocus=null,currentPanel='',currentCase=null,chosen=new Set(),toastTimer;
function esc(t){return String(t).replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]));}
function fmt(n){return Number(n).toLocaleString('ru-RU');}
function save(){try{localStorage.setItem('caseclash.v3',JSON.stringify(state));}catch{toastMsg('Не удалось сохранить: проверь доступ браузера к хранилищу.');}sync();}
function sprite(x,y,w,h,label=''){return `<span class="sprite" ${label?`role="img" aria-label="${esc(label)}"`:'aria-hidden="true"'} style="--x:${x}px;--y:${y}px;--w:${w}px;--h:${h}px"></span>`;}
function caseArt(i){return `<div class="caseArt">${sprite([168,309,450,592,733,875][i],494,128,111,cases[i][0]+' — кейс')}</div>`;}
function weapon(i){return `<div class="weaponArt">${sprite([20,145,269,393,518,649,774,902][i],732,105,69,skins[i][0]+' '+skins[i][1])}</div>`;}
function skinCard(item,select=false){return `<div class="panelCard inventoryCard">${select?`<label><input type="checkbox" aria-label="Выбрать ${esc(skins[item.skin][1])}" onchange="toggleItem('${item.id}',this.checked)"> Выбрать</label>`:''}${weapon(item.skin)}<b>${esc(skins[item.skin][0])} · ${esc(skins[item.skin][1])}</b><p>${fmt(skins[item.skin][3])} очков</p>${select?'':`<button class="btn" onclick="exchangeItem('${item.id}')">Обменять · ${sellValue(item.skin)} монет</button>`}</div>`;}
function item(skin){return {id:crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2),skin,at:Date.now()};}
function pick(){const r=Math.random();return r<.3?0:r<.5?7:r<.7?2:r<.83?1:r<.92?4:r<.965?5:r<.989?6:3;}
function sellValue(i){return Math.max(5,Math.round(skins[i][3]/1000));}
function toastMsg(t){clearTimeout(toastTimer);$('#toast').textContent=t;$('#toast').classList.add('show');toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),2800);}
function sync(){if($('#coinTop'))$('#coinTop').textContent=fmt(state.coins);if($('#gemTop'))$('#gemTop').textContent=fmt(state.gems);if($('#profileName'))$('#profileName').textContent=state.name;if($('#openCount'))$('#openCount').textContent=Math.min(state.opens,3);if($('#winCount'))$('#winCount').textContent=Math.min(state.wins,1);const t=$('#tasksHome');if(t)t.innerHTML=taskRows();if($('#dailyTime'))$('#dailyTime').textContent=state.daily===new Date().toDateString()?'Получено сегодня':'Забрать +100 монет';}
function taskRows(){return [{id:'opens',label:'Открой 3 кейса',v:state.opens,n:3,reward:50},{id:'wins',label:'Выиграй 1 баттл',v:state.wins,n:1,reward:75},{id:'ads',label:'Посмотри рекламу',v:state.ads,n:1,reward:25}].map((t,i)=>`<button class="task" onclick="${t.id==='ads'&&t.v<1?'rewardAd()':`claimTask('${t.id}')`}"><span class="check" style="background:${['#215d42','#563670','#6a29a3'][i]}">${icon(i===2?'play':'check')}</span><span class="taskName">${t.label}</span><span class="reward"><span class="prog">${state.claims.includes(t.id)?'Готово':Math.min(t.v,t.n)+' / '+t.n}</span>　${coin} +${t.reward}</span></button>`).join('');}
function render(){
 $('#caseRow').innerHTML=cases.map((c,i)=>`<button class="caseCard" onclick="openCase('${c[0]}',${c[2]})"><h3>${c[0]}</h3>${caseArt(i)}<div class="price">${coin} ${c[2]}</div></button>`).join('');
 $('#dropRow').innerHTML=skins.map((s,i)=>`<button class="drop ${[3,5].includes(i)?'gold':[1,6].includes(i)?'red':[2,7].includes(i)?'blue':''}" onclick="skinInfo(${i})">${weapon(i)}<b>${s[0]}</b><small>${s[1]}</small><div class="value">₽ ${fmt(s[3])}</div></button>`).join('');
 $$('.sideNav .ic').forEach((el,i)=>{el.style.backgroundPosition='-24px -'+[120,167,214,261,308,355,402,449,496,543][i]+'px';});const nav=['home','case','battle','upgrade','contract','shop','tasks','refs','top','support'];$$('.sideNav .ic').forEach((el,i)=>el.innerHTML=icon(nav[i]));$$('.topNav .ni').forEach((el,i)=>el.innerHTML=icon(['case','upgrade','battle','contract','event'][i]));
 $('.topNav button').setAttribute('onclick',"showPanel('cases')");
 $('.daily').innerHTML=icon('gift')+'<b>Ежедневные<br>награды</b><div class="time" id="dailyTime"></div>';$('.daily').setAttribute('onclick','dailyReward()');asButton($('.daily'),'Ежедневная награда');
 $('.chip.p').innerHTML=icon('gem')+' <span id="gemTop"></span><span class="plus">+</span>';$('.chip.g').innerHTML=coin+' <span id="coinTop"></span><span class="plus">+</span>';
 $$('.chip').forEach(el=>{el.setAttribute('onclick',"showPanel('shop')");asButton(el,'Пополнить демо-баланс');});
 $('.profile').insertAdjacentHTML('beforebegin',`<button class="bell" aria-label="Уведомления" onclick="showPanel('notifications')">${icon('bell')}</button>`);
 $('.profile b').id='profileName';asButton($('.profile'),'Профиль');
 $('.heroBtns .gold').innerHTML=coin+' 299';$('.heroBtns .gold').setAttribute('onclick',"openCase('CROWN',299)");
 $$('.sliderCtl button').forEach((b,i)=>{b.setAttribute('onclick',`heroSlide(${i?1:-1})`);b.setAttribute('aria-label',i?'Следующий кейс':'Предыдущий кейс');});
 $('.pvp').innerHTML=icon('battle')+' PVP';$('.pvp').setAttribute('onclick',"showPanel('battle')");
 $$('.mode').forEach((el,i)=>{el.querySelector('.crown').innerHTML=icon(i===0?'gem':'crown');el.setAttribute('onclick',`showBattle('${i+1}x${i+1}')`);asButton(el,`Баттл ${i+1}x${i+1}`);});
 $$('.infoCard h3').forEach((h,i)=>{h.innerHTML=icon(['battle','tasks','refs'][i])+['СОБЫТИЯ','ЗАДАНИЯ','РЕФЕРАЛЫ'][i];});
 const tasks=$$('.infoCard')[1];tasks.querySelectorAll('.task').forEach(e=>e.remove());tasks.insertAdjacentHTML('beforeend','<div class="tasks-home" id="tasksHome"></div>');
 $('.copy').innerHTML=icon('copy');$('.copy').setAttribute('aria-label','Скопировать приглашение');
 $$('.stat .si').forEach((el,i)=>el.innerHTML=sprite([27,264,524,781][i],1376,48,49));
 $('.footer').innerHTML=`<div class="footerLogo">CASE CLASH</div><div class="footerLinks">© 2026 Case Clash. Все права защищены.<br><button onclick="showPanel('terms')">Пользовательское соглашение</button>　<button onclick="showPanel('privacy')">Политика конфиденциальности</button><br><span class="demo-label">Демо · виртуальные предметы · без ставок и вывода</span></div><div class="social">${['send','play','music','chat'].map((n,i)=>`<button aria-label="${['Telegram','YouTube','TikTok','Discord'][i]}" onclick="showSocial('${['Telegram','YouTube','TikTok','Discord'][i]}')">${icon(n)}</button>`).join('')}<button class="lang" onclick="showPanel('language')">RU⌄</button></div>`;
 $('#modal').setAttribute('role','dialog');$('#modal').setAttribute('aria-modal','true');$('#modal').setAttribute('aria-labelledby','modalTitle');$('.x').setAttribute('aria-label','Закрыть');$('#toast').setAttribute('role','status');installMobile();sync();resize();
}
function asButton(el,name){el.setAttribute('role','button');el.setAttribute('tabindex','0');el.setAttribute('aria-label',name);el.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();el.click();}});}
function resize(){document.documentElement.style.setProperty('--scale',1);}
window.addEventListener('resize',resize);
function openModal(title,html,panel=''){if(busy){toastMsg('Дождись завершения текущего действия');return false;}if(!$('#modal').classList.contains('show'))lastFocus=document.activeElement;if($('#modal').classList.contains('show')&&!goingBack&&panel!==currentPanel&&modalLocation)sheetHistory.push(modalLocation);goingBack=false;modalLocation={panel,case:currentCase?{...currentCase}:null,mode:typeof battleMode==='undefined'?'1x1':battleMode};currentPanel=panel;$('.modalBox').dataset.panel=panel;$('.sheetBack').classList.toggle('visible',sheetHistory.length>0);setMobileActive(panel);$('#modalTitle').textContent=title;$('#modalBody').innerHTML=html;$('#modal').classList.add('show');$('.modalBox').scrollTop=0;$('.x').focus({preventScroll:true});document.body.style.overflow='hidden';return true;}
function closeModal(){if(busy){toastMsg('Дождись завершения анимации');return;}$('#modal').classList.remove('show');document.body.style.overflow='';currentPanel='';sheetHistory=[];modalLocation=null;setMobileActive('home');lastFocus?.focus?.({preventScroll:true});}
function showHome(){closeModal();if(!busy)window.scrollTo({top:0,behavior:'smooth'});}
$('#modal').addEventListener('click',e=>{if(e.target===$('#modal'))closeModal();});
document.addEventListener('keydown',e=>{if(!$('#modal').classList.contains('show'))return;if(e.key==='Escape')closeModal();if(e.key==='Tab'){const els=[...$('#modal').querySelectorAll('button:not(:disabled),input,textarea,[tabindex="0"]')].filter(x=>x.offsetParent!==null);if(!els.length)return;const first=els[0],last=els.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});
function heroSlide(d){if(busy)return;slide=(slide+d+6)%6;const names=['CROWN','ELITE','NIGHTMARE','LEGEND','DRAGON','INFINITY'];const prices=[299,49,149,299,499,999];$('.hero h1').textContent=names[slide];$('.hero h1').style.fontSize=slide===2?'47px':slide===5?'55px':'72px';$('.sliderCtl span').textContent=`${slide+1} / 6`;$('.heroBtns .gold').innerHTML=coin+' '+prices[slide];$$('.heroBtns button').forEach(b=>b.setAttribute('onclick',`openCase('${names[slide]}',${prices[slide]})`));$('.caseScene').style.filter=slide?`hue-rotate(${[0,175,240,0,315,180][slide]}deg)`:'';}
function openCase(name,price){if(busy)return;currentCase={name,price};const previewItems=Array.from({length:7},(_,i)=>i%8);openModal(name+' CASE',`<p>${price?`Открытие: ${price} виртуальных монет`:'Бесплатный кейс'} · баланс ${fmt(state.coins)}</p><div class="roulette"><div class="marker"></div><div class="track" id="track">${previewItems.map(rollCard).join('')}</div></div><div class="result" id="result"></div><div class="actions"><button id="spinButton" class="btn primary" onclick="spin()">ОТКРЫТЬ${price?' · '+price:''}</button><button class="btn" onclick="rewardAd()">+25 ЗА РЕКЛАМУ</button><button class="btn" onclick="showPanel('shop')">Пополнить демо-баланс</button></div><details class="caseDetails"><summary>Что может выпасть · шансы</summary><p class="notice">Учебная демоверсия. Предметы виртуальные, продажи и вывода нет. Вероятности: Redline 30%, Chameleon 20%, Printstream 20%, Asiimov 13%, Fade 9%, Gold Arabesque 4,5%, Howl 2,4%, Doppler 1,1%.</p></details>`,'case');}
function rollCard(i){return `<div class="roll"><div class="rollArt">${weapon(i)}</div><b>${skins[i][0]}<br>${skins[i][1]}</b></div>`;}
function spin(){if(busy||currentPanel!=='case')return;const c={...currentCase};if(state.coins<c.price){toastMsg('Не хватает монет. Открой бесплатный STARTER или пополни демо-баланс.');return;}busy=true;state.coins-=c.price;const won=pick(),items=Array.from({length:36},()=>pick());items[28]=won;const reward=item(won);state.inv.push(reward);state.opens++;save();const track=$('#track');track.innerHTML=items.map(rollCard).join('');track.style.transition='none';track.style.transform='translateX(0)';$('#spinButton').disabled=true;$('#result').classList.remove('show');const targetRect=track.children[28].getBoundingClientRect(),markerRect=$('.marker').getBoundingClientRect();const shift=targetRect.left+targetRect.width/2-markerRect.left-markerRect.width/2;requestAnimationFrame(()=>requestAnimationFrame(()=>{track.style.transition='transform 3.6s cubic-bezier(.1,.68,.12,1)';track.style.transform=`translateX(-${shift}px)`;}));setTimeout(()=>{busy=false;$('#result').classList.add('show');$('#result').innerHTML=`<span class="tag">ПРЕДМЕТ СОХРАНЁН</span><h3>${skins[won][0]} · ${skins[won][1]}</h3>${weapon(won)}<div class="actions"><button class="btn primary" onclick="showPanel('inventory')">В ИНВЕНТАРЬ</button><button class="btn" onclick="openCase('${c.name}',${c.price})">ЕЩЁ РАЗ</button></div>`;$('#spinButton').disabled=true;},3700);}
function showPanel(type){if(busy){toastMsg('Дождись завершения текущего действия');return;}if(type==='battle'){showBattle('1x1');return;}chosen=new Set();const title={menu:'МЕНЮ',cases:'ВСЕ КЕЙСЫ',inventory:'ИНВЕНТАРЬ',upgrade:'АПГРЕЙД',contract:'КОНТРАКТ',shop:'ДЕМО-БАЛАНС',tasks:'ЗАДАНИЯ',refs:'РЕФЕРАЛЫ',top:'ТОП ИГРОКОВ',support:'ПОДДЕРЖКА',events:'WINTER EVENT',profile:'ПРОФИЛЬ',notifications:'УВЕДОМЛЕНИЯ',terms:'УСЛОВИЯ ДЕМОВЕРСИИ',privacy:'КОНФИДЕНЦИАЛЬНОСТЬ',language:'ЯЗЫК'}[type]||'CASE CLASH';let html='';
 switch(type){
 case 'menu':html=`<div class="menuGrid">${[['upgrade','upgrade','Апгрейд'],['contract','contract','Контракт'],['events','event','События'],['tasks','tasks','Задания'],['refs','refs','Рефералы'],['shop','shop','Баланс'],['profile','home','Профиль'],['notifications','bell','Уведомления'],['top','top','Рейтинг'],['support','support','Поддержка']].map(([p,i,t])=>`<button class="btn" onclick="showPanel('${p}')">${icon(i)}${t}</button>`).join('')}<button class="btn" onclick="dailyReward()">${icon('gift')}Награда дня</button><button class="btn" onclick="rewardAd()">${icon('play')}Реклама · +25</button></div>`;break;
 case 'cases':html=`<div class="grid2">${cases.map((c,i)=>`<div class="panelCard"><h3>${c[0]}</h3>${caseArt(i)}<button class="btn primary" onclick="openCase('${c[0]}',${c[2]})">ОТКРЫТЬ · ${c[2]}</button></div>`).join('')}</div>`;break;
 case 'inventory':html=`<p>${state.inv.length} предметов · ${fmt(state.coins)} монет</p><div class="grid2">${state.inv.slice().reverse().map(x=>skinCard(x)).join('')||empty()}</div><div class="actions"><button class="btn" onclick="showPanel('upgrade')">Апгрейд</button><button class="btn" onclick="showPanel('contract')">Контракт</button></div>`;break;
 case 'upgrade':case 'contract':html=`<p>${type==='upgrade'?'Выбери один предмет. Шанс 50%: при успехе получишь более дорогой предмет, при неудаче выбранный предмет исчезнет. Самый дорогой предмет улучшить нельзя.':'Выбери ровно три предмета: они будут обменены на один случайный предмет. Результат может быть дешевле исходных.'}</p><div class="grid2">${state.inv.map(x=>skinCard(x,true)).join('')||empty()}</div><div class="actions"><button id="selectionAction" class="btn primary" onclick="${type==='upgrade'?'upgradeSelected()':'contractSelected()'}" disabled>${type==='upgrade'?'АПГРЕЙД · 50%':'СОЗДАТЬ КОНТРАКТ'}</button><button class="btn" onclick="showPanel('inventory')">Инвентарь</button></div>`;break;
 case 'shop':html=`<p>Баланс: ${fmt(state.coins)} монет · ${fmt(state.gems)} кристаллов. Только виртуальная валюта: никаких платежей.</p><div class="grid2"><div class="panelCard"><h3>Тестовый запас</h3><p>Бесплатно добавь 1 000 монет для проверки всех режимов.</p><button class="btn primary" onclick="addDemoCoins()">+1 000 ДЕМО-МОНЕТ</button></div><div class="panelCard"><h3>Кристаллы</h3><p>Обменяй 100 кристаллов на 100 монет.</p><button class="btn" onclick="convertGems()" ${state.gems<100?'disabled':''}>ОБМЕНЯТЬ 100</button></div></div><div class="actions"><button class="btn" onclick="dailyReward()">Ежедневная награда</button><button class="btn" onclick="rewardAd()">Реклама · +25</button></div>`;break;
 case 'tasks':html=`<p>Награду за каждый этап можно получить один раз.</p>${taskRows()}`;break;
 case 'refs':html=`<p>Приглашение на эту демоверсию:</p><div class="refbox"><input id="refModal" value="${esc(refUrl())}" readonly aria-label="Ссылка приглашения"><button class="copy" aria-label="Скопировать приглашение" onclick="copyRef()">${icon('copy')}</button></div><p class="notice">В демо приглашение открывает проект. Учёт друзей и начисление 10% требуют сервера и пока не подключены.</p><div class="panelCard"><h3>Приглашения</h3><p>Ссылка скопирована: ${state.refClicks} раз</p><p>Подтверждённых друзей: 0 · Доход: 0</p></div>`;break;
 case 'top':html=`<p class="notice">Демонстрационный рейтинг ботов. Твои показатели сохраняются на устройстве.</p><div class="grid2">${[['NOVA',82],['GHOST',64],['VIOLET',53],[state.name,state.wins]].map((u,i)=>`<div class="panelCard"><h3>${i+1}. ${esc(u[0])}</h3><p>${u[1]} побед${i<3?' · демо-бот':''}</p></div>`).join('')}</div>`;break;
 case 'support':html=`<p>Опиши проблему. Обращение сохранится на этом устройстве; отправка в службу поддержки пока не подключена.</p><label class="field">Сообщение<textarea id="supportText" placeholder="Что случилось?" maxlength="2000"></textarea></label><button class="btn primary" onclick="saveTicket()">СОХРАНИТЬ ОБРАЩЕНИЕ</button><div class="grid2">${state.tickets.map(t=>`<div class="panelCard"><b>Обращение ${t.id}</b><p>${esc(t.text)}</p><span class="tag">Локальный черновик</span></div>`).join('')}</div>`;break;
 case 'events':html=`<div class="panelCard"><h3>WINTER EVENT</h3>${caseArt(5)}<p>Открой 5 любых кейсов и получи INFINITY бесплатно. Прогресс: ${Math.min(state.opens,5)} / 5.</p><button class="btn primary" onclick="claimEvent()" ${state.event||state.opens<5?'disabled':''}>${state.event?'НАГРАДА ПОЛУЧЕНА':'ПОЛУЧИТЬ ПРЕДМЕТ'}</button></div><p class="notice">Демонстрационное событие без календарного ограничения.</p>`;break;
 case 'profile':html=`<label class="field">Имя<input id="nameInput" value="${esc(state.name)}" maxlength="20"></label><button class="btn primary" onclick="saveName()">СОХРАНИТЬ</button><div class="grid2"><div class="panelCard"><h3>${state.inv.length} предметов</h3><p>Открыто кейсов: ${state.opens}<br>Побед: ${state.wins}<br>Баттлов: ${state.battles.length}</p><button class="btn" onclick="showPanel('inventory')">ИНВЕНТАРЬ</button></div><div class="panelCard"><h3>${fmt(state.coins)} монет</h3><p>${fmt(state.gems)} кристаллов</p><button class="btn" onclick="showPanel('shop')">ПОПОЛНИТЬ</button></div></div>`;break;
 case 'notifications':html=`<div class="panelCard"><h3>Добро пожаловать в CASE CLASH</h3><p>Забери ежедневные 100 монет и открой первый кейс.</p><button class="btn primary" onclick="dailyReward()">ЗАБРАТЬ НАГРАДУ</button></div><div class="panelCard"><h3>Твоя активность</h3><p>Открыто ${state.opens} кейсов. В инвентаре ${state.inv.length} предметов.</p><button class="btn" onclick="showPanel('tasks')">ПРОВЕРИТЬ ЗАДАНИЯ</button></div>`;break;
 case 'terms':html='<p>CASE CLASH — бесплатная интерактивная демоверсия. Все балансы и предметы виртуальные. Денежных ставок, покупок, продажи предметов и вывода средств нет. Показанные рублёвые значения — иллюстративные подписи референса, а не рыночные предложения.</p><p>Баттлы проходят против демо-ботов. Реклама симулируется. Статистика главной страницы демонстрационная.</p>';break;
 case 'privacy':html='<p>Имя, баланс, предметы, задания и черновики обращений сохраняются в localStorage этого браузера. Серверная регистрация и отправка обращений отсутствуют. Очистка данных сайта удалит локальный прогресс.</p>';break;
 case 'language':html='<p>Интерфейс демоверсии доступен на русском. Названия кейсов и предметов сохранены на английском.</p><button class="btn primary" onclick="closeModal()">РУССКИЙ · ВЫБРАН</button>';break;
 }
 openModal(title,html,type);
}
function empty(){return '<div class="empty">Инвентарь пуст.<br><button class="btn primary" onclick="openCase(\'STARTER\',0)">ОТКРЫТЬ БЕСПЛАТНЫЙ КЕЙС</button></div>';}
function toggleItem(id,on){if(on)chosen.add(id);else chosen.delete(id);$('#selectionAction').disabled=chosen.size!==(currentPanel==='upgrade'?1:3);}
function upgradeSelected(){if(busy||chosen.size!==1)return;const id=[...chosen][0],ix=state.inv.findIndex(x=>x.id===id);if(ix<0)return;const source=state.inv[ix],better=skins.map((s,i)=>i).filter(i=>skins[i][3]>skins[source.skin][3]);if(!better.length){toastMsg('Это уже самый дорогой предмет');return;}state.inv.splice(ix,1);const ok=Math.random()<.5,target=better[Math.floor(Math.random()*better.length)];if(ok)state.inv.push(item(target));save();openModal(ok?'АПГРЕЙД УСПЕШЕН':'АПГРЕЙД НЕ УДАЛСЯ',`${ok?weapon(target):weapon(source.skin)}<h3>${ok?skins[target][0]+' · '+skins[target][1]:'Исходный предмет израсходован'}</h3><p>Шанс составлял 50%.</p><button class="btn primary" onclick="showPanel('inventory')">ИНВЕНТАРЬ</button>`,'result');}
function contractSelected(){if(busy||chosen.size!==3)return;const ids=[...chosen];if(ids.some(id=>!state.inv.some(x=>x.id===id)))return;state.inv=state.inv.filter(x=>!chosen.has(x.id));const won=pick();state.inv.push(item(won));save();openModal('КОНТРАКТ ВЫПОЛНЕН',`${weapon(won)}<h3>${skins[won][0]} · ${skins[won][1]}</h3><p>Три выбранных предмета обменены на один. Предмет сохранён.</p><button class="btn primary" onclick="showPanel('inventory')">ИНВЕНТАРЬ</button>`,'result');}
function exchangeItem(id){const ix=state.inv.findIndex(x=>x.id===id);if(ix<0)return;const x=state.inv.splice(ix,1)[0];state.coins+=sellValue(x.skin);save();showPanel('inventory');toastMsg('Предмет обменян на виртуальные монеты');}
function addDemoCoins(){state.coins+=1000;save();showPanel('shop');toastMsg('+1 000 демо-монет');}
function convertGems(){if(state.gems<100)return;state.gems-=100;state.coins+=100;save();showPanel('shop');}
function dailyReward(){if(busy)return;const today=new Date().toDateString();if(state.daily===today){toastMsg('Сегодня награда уже получена');return;}state.daily=today;state.coins+=100;save();toastMsg('Ежедневная награда: +100 монет');}
function claimTask(id){if(busy)return;const t={opens:[state.opens,3,50],wins:[state.wins,1,75],ads:[state.ads,1,25]}[id];if(!t)return;if(state.claims.includes(id)){toastMsg('Награда уже получена');return;}if(t[0]<t[1]){showPanel('tasks');toastMsg('Сначала выполни задание');return;}state.claims.push(id);state.coins+=t[2];save();if(currentPanel==='tasks')showPanel('tasks');toastMsg(`Задание выполнено: +${t[2]} монет`);}
function rewardAd(){if(busy)return;openModal('РЕКЛАМНАЯ ПАУЗА',`<div class="empty"><h3>CASE CLASH</h3><p>Это симуляция rewarded-рекламы.<br>Рекламная сеть не подключена.</p><p id="adCountdown">До награды: 5 сек.</p><button id="adClaim" class="btn primary" disabled onclick="finishAd()">ПОЛУЧИТЬ +25</button></div>`,'ad');busy=true;let left=5;const timer=setInterval(()=>{left--;$('#adCountdown').textContent=left?`До награды: ${left} сек.`:'Просмотр завершён';if(!left){clearInterval(timer);busy=false;$('#adClaim').disabled=false;}},1000);}
function finishAd(){if(busy||currentPanel!=='ad'||$('#adClaim').disabled)return;$('#adClaim').disabled=true;state.coins+=25;state.ads++;save();openModal('НАГРАДА ПОЛУЧЕНА','<h3 class="success">+25 монет</h3><p>Баланс сохранён.</p><button class="btn primary" onclick="showPanel(\'cases\')">К КЕЙСАМ</button>','result');}
function claimEvent(){if(busy||state.event||state.opens<5)return;state.event=true;const won=pick();state.inv.push(item(won));save();openModal('WINTER · НАГРАДА',`${weapon(won)}<h3>${skins[won][0]} · ${skins[won][1]}</h3><button class="btn primary" onclick="showPanel('inventory')">ИНВЕНТАРЬ</button>`,'result');}
function saveName(){const value=$('#nameInput').value.trim();if(!value){toastMsg('Введи имя');return;}state.name=value.slice(0,20);save();toastMsg('Имя сохранено');}
function saveTicket(){const value=$('#supportText').value.trim();if(value.length<5){toastMsg('Опиши проблему подробнее');return;}state.tickets.unshift({id:Date.now().toString(36).toUpperCase(),text:value.slice(0,2000)});save();showPanel('support');toastMsg('Обращение сохранено на устройстве');}
function refUrl(){return 'https://htmlpreview.github.io/?https://github.com/sadadafs8-pixel/chatruletk/blob/case-clash-demo/case-clash/index.html';}
async function copyRef(){try{await navigator.clipboard.writeText(refUrl());state.refClicks++;save();toastMsg('Ссылка на демоверсию скопирована');}catch{showPanel('refs');$('#refModal').select();toastMsg('Выделена ссылка: скопируй её вручную');}}
function showSocial(name){openModal(name,`<p>Официальный канал CASE CLASH в ${esc(name)} пока не подключён. Ты можешь поделиться самой демоверсией.</p><button class="btn primary" onclick="copyRef()">СКОПИРОВАТЬ ССЫЛКУ НА ПРОЕКТ</button>`,'social');}
function skinInfo(i){openModal(skins[i][0],`${weapon(i)}<h3>${skins[i][1]}</h3><p>${fmt(skins[i][3])} очков коллекции</p><p class="notice">Виртуальный демонстрационный предмет. Рублёвые подписи на главной повторяют референс; реальной продажи и вывода нет.</p><button class="btn primary" onclick="showPanel('cases')">ОТКРЫТЬ КЕЙС</button>`,'skin');}
let battleMode='1x1';
function showBattle(mode){battleMode=mode;openModal('CASE BATTLE',`<p>Демо-баттл против ботов · вход 49 монет · баланс ${fmt(state.coins)}</p><div class="actions">${['1x1','2x2','3x3'].map(m=>`<button class="btn ${m===mode?'primary selected':''}" onclick="showBattle('${m}')">${m}</button>`).join('')}</div><p>${mode==='1x1'?'Один игрок против одного':mode==='2x2'?'Ты и один бот против двух ботов':'Ты и два бота против трёх ботов'}. Выигрывает команда с большей суммой очков предметов.</p><button id="battleStart" class="btn primary" onclick="startBattle()">НАЧАТЬ БАТТЛ · 49</button><div id="battleLog"></div><h3>История</h3>${state.battles.slice(-5).reverse().map(b=>`<div class="panelCard"><b>${b.mode} · ${b.a===b.b?'Ничья':b.won?'Победа':'Поражение'}</b><p>${fmt(b.a)} : ${fmt(b.b)} очков · ${new Date(b.at).toLocaleTimeString('ru-RU')}</p></div>`).join('')||'<p>Пока нет завершённых баттлов.</p>'}`,'battle');}
function startBattle(){if(busy||currentPanel!=='battle')return;if(state.coins<49){toastMsg('Нужно 49 монет. Пополни демо-баланс в магазине.');return;}const n=parseInt(battleMode),left=Array.from({length:n},()=>pick()),right=Array.from({length:n},()=>pick()),a=left.reduce((v,i)=>v+skins[i][3],0),b=right.reduce((v,i)=>v+skins[i][3],0),won=a>b,tie=a===b;state.coins-=49;if(won){state.wins++;state.coins+=98;state.inv.push(item(left[0]));}else if(tie)state.coins+=49;state.battles.push({mode:battleMode,a,b,won,tie,at:Date.now()});save();busy=true;$('#battleStart').disabled=true;$('#battleLog').innerHTML='<div class="empty">Кейсы открываются…</div>';setTimeout(()=>{busy=false;$('#battleLog').innerHTML=`<div class="battleSlots"><div class="battleResult"><h3>${esc(state.name)}${n>1?' + боты':''}</h3>${left.map(weapon).join('')}<b>${fmt(a)} очков</b></div><div class="battleResult"><h3>Команда ботов</h3>${right.map(weapon).join('')}<b>${fmt(b)} очков</b></div></div><h3 class="${won||tie?'success':'danger'}">${won?'ПОБЕДА · +98 монет и предмет':tie?'НИЧЬЯ · взнос возвращён':'ПОРАЖЕНИЕ'}</h3><button class="btn primary" onclick="showBattle('${battleMode}')">ЕЩЁ БАТТЛ</button>`;},1800);}
let sheetHistory=[],modalLocation=null,goingBack=false;
function setMobileActive(panel){document.querySelectorAll('.mobileNav button').forEach(b=>{const active=b.dataset.panel===(['home','cases','battle','inventory'].includes(panel)?panel:'menu');b.classList.toggle('active',active);if(active)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});}
function sheetBack(){if(busy){toastMsg('Дождись завершения анимации');return;}const prev=sheetHistory.pop();if(!prev){closeModal();return;}goingBack=true;if(prev.panel==='case'&&prev.case)openCase(prev.case.name,prev.case.price);else if(prev.panel==='battle')showBattle(prev.mode);else if(['result','skin','social','ad'].includes(prev.panel))showPanel('inventory');else showPanel(prev.panel);}
function installMobile(){
 $('.top').insertAdjacentHTML('afterbegin','<button class="mobileLogo" aria-label="На главную" onclick="showHome()"></button>');
 document.body.insertAdjacentHTML('beforeend',`<nav class="mobileNav" aria-label="Основная навигация">${[['home','home','Главная'],['cases','case','Кейсы'],['battle','battle','Баттлы'],['inventory','contract','Инвентарь'],['menu','tasks','Меню']].map(([p,i,t])=>`<button data-panel="${p}" class="${p==='home'?'active':''}" onclick="${p==='home'?'showHome()':`showPanel('${p}')`}">${icon(i)}<span>${t}</span></button>`).join('')}</nav>`);
 $('.modalTop').insertAdjacentHTML('afterbegin','<button class="sheetBack" aria-label="Назад" onclick="sheetBack()">‹</button>');
}
render();
