const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
const memory=new Map(),timers=[];
const el={disabled:false,hidden:false,innerHTML:'',textContent:'',className:'',classList:{add(){},remove(){},toggle(){}},style:{setProperty(){}},scrollIntoView(){},insertAdjacentHTML(){},addEventListener(){}};
const context={console,crypto:require('crypto').webcrypto,structuredClone,Date,Math,Uint32Array,requestAnimationFrame(){},setTimeout:f=>{timers.push(f);return timers.length},clearTimeout(){},setInterval(){},clearInterval(){},navigator:{},localStorage:{getItem:k=>memory.get(k)||null,setItem:(k,v)=>memory.set(k,v),removeItem:k=>memory.delete(k)},document:{querySelector:()=>el,querySelectorAll:()=>[],addEventListener(){}},window:{addEventListener(){}},assert};
vm.createContext(context);vm.runInContext(['app.js','config.js','services.js','game.js'].map(f=>fs.readFileSync(__dirname+'/'+f,'utf8')).join('\n').replace('finishInit();',''),context);
vm.runInContext(`sync=()=>{};toastMsg=()=>{};scene=()=>{};inventory=()=>{};wheelPage=()=>{};showUpgrade=()=>{};
(async()=>{
 const reset=()=>{state=fresh();localStorage.setItem(CONFIG.key,JSON.stringify(state));busy=false;};
 reset();currentPanel='case';currentCase={name:'ELITE',price:49,index:1,token:null};quantity=3;await spin();assert.equal(state.inv.length,3);assert.equal(state.opens,3);assert.equal(state.dailyStats.opens,3);assert.equal(state.passXP,state.xp);assert.ok(state.achievements.includes('FIRST DROP'));const after=state.inv.length;await spin();assert.equal(state.inv.length,after);busy=false;quantity=5;await spin();assert.equal(state.inv.length,8);assert.equal(state.opens,8);
 reset();state.coins=0;localStorage.setItem(CONFIG.key,JSON.stringify(state));quantity=1;await spin();assert.equal(state.inv.length,0);assert.equal(state.coins,0);assert.equal(busy,false);
 reset();currentPanel='upgrade';await transact('seed item',s=>s.inv.push(item(0)));upgradeSource=state.inv[0].id;upgradeTarget=1;const originalRandom=randomUnit;randomUnit=()=>0;await performUpgrade();assert.equal(state.inv.length,1);assert.equal(state.inv[0].skin,1);assert.equal(state.upgradeWins,1);assert.equal(state.dailyStats.upgrades,1);busy=false;upgradeSource=state.inv[0].id;upgradeTarget=3;randomUnit=()=>.999999;await performUpgrade();assert.equal(state.inv.length,0);assert.equal(state.upgrades,2);randomUnit=originalRandom;
 for(const mode of ['1x1','2x2','3x3']){reset();currentPanel='battle';battleMode=mode;await startBattle();assert.equal(state.battles.length,1);assert.equal(state.battles[0].rounds.length,3);assert.equal(state.battles[0].rounds[0].left.length,parseInt(mode));assert.equal(state.battles[0].rounds[0].right.length,parseInt(mode));assert.equal(state.inv.length,state.battles[0].won?3:0);assert.ok(state.coins>=0);}
 reset();adProvider.watch=async(placement,callback)=>callback({id:'same-receipt',placement});currentPanel='wheel';await runAd('wheel');assert.equal(state.wheel.used,1);assert.equal(state.ads,1);await spinWheel();const bal=state.coins;busy=false;await spinWheel();assert.equal(state.coins,bal);busy=false;await runAd('wheel');assert.equal(state.wheel.used,1);assert.equal(state.ads,1);
 for(let i=1;i<3;i++){adProvider.watch=async(placement,cb)=>cb({id:'receipt-'+i,placement});await runAd('wheel');await spinWheel();busy=false;}assert.equal(state.wheel.used,3);await runAd('wheel');assert.equal(state.wheel.used,3);assert.equal(state.ads,3);
 reset();const a=await paymentProvider.createPayment('g80');await Promise.all([paymentProvider.complete(a.id,'success'),paymentProvider.complete(a.id,'success')]);assert.equal(state.gems,80);assert.equal((await paymentProvider.verifyPayment(a.id)).verified,true);
 const malformed=normalize({dailyStats:{id:day(),claimed:null,opens:NaN},wheel:{day:day(),used:-2},weekly:{id:week(),score:NaN},login:{last:0,streak:99},inv:[null,{id:'valid',skin:0}],caseTokens:[null,{id:'bad',case:99}],payments:[null,{id:'bad',productId:'bad'}]});assert.equal(malformed.inv.length,1);assert.equal(malformed.dailyStats.opens,0);assert.equal(malformed.wheel.used,0);assert.equal(malformed.caseTokens.length,0);
 const rollover=normalize({...state,dailyStats:{id:day()-1,opens:9,claimed:['opens']},wheel:{day:day()-1,used:3},weekly:{id:week()-1,score:99}});assert.equal(rollover.dailyStats.opens,0);assert.equal(rollover.wheel.used,0);assert.equal(rollover.weekly.score,0);
 assert.ok(loginReward(7).case);assert.ok(loginReward(7).cosmetic);console.log('PASS: actual case actions x3/x5, inventory/stats/XP propagation, busy replay, insufficient funds, both upgrade outcomes, all team sizes/rounds, wheel receipt replay/quota, concurrent payment callbacks/verification, malformed nested state and day/week rollover');
})().catch(e=>{console.error(e);throw e;});`,context);
