'use strict';
// Central demo catalog. Money is never collected; only simulated success grants goods.

const day=()=>Math.floor(Date.now()/86400000), week=()=>Math.floor((day()+3)/7), uid=()=>crypto.randomUUID();
function randomUnit(){const a=new Uint32Array(1);crypto.getRandomValues(a);return a[0]/4294967296;}
function weighted(weights,r=randomUnit()){let sum=0;const t=r*weights.reduce((a,b)=>a+b,0);for(let i=0;i<weights.length;i++){sum+=weights[i];if(t<sum)return i;}return weights.length-1;}
function fresh(){return {...structuredClone(defaults),version:4,coins:1000,gems:0,xp:0,passXP:0,upgrades:0,upgradeWins:0,revision:0,paidCoins:0,weekly:{id:week(),score:0},dailyStats:{id:day(),opens:0,wins:0,ads:0,upgrades:0,claimed:[]},login:{last:-1,streak:0},wheel:{day:day(),used:0,credit:null},caseTokens:[],payments:[],adReceipts:[],premiumUntil:0,passOwned:false,passClaims:[],cosmetics:[],frame:'default',achievements:[],activity:[]};}
function normalize(raw){const s={...fresh(),...raw};for(const k of ['coins','gems','xp','passXP','opens','wins','upgrades','upgradeWins','paidCoins','revision','premiumUntil'])if(!Number.isFinite(s[k])||s[k]<0)s[k]=0;
 for(const k of ['inv','battles','claims','tickets','caseTokens','payments','adReceipts','passClaims','cosmetics','achievements','activity'])if(!Array.isArray(s[k]))s[k]=[];
 s.caseTokens=s.caseTokens.filter(t=>t&&typeof t.id==='string'&&Number.isInteger(t.case)&&cases[t.case]);s.payments=s.payments.filter(p=>p&&typeof p.id==='string'&&product(p.productId)&&['pending','success','failure','cancel'].includes(p.status));
 s.inv=s.inv.filter((x,i,a)=>x&&Number.isInteger(x.skin)&&skins[x.skin]&&typeof x.id==='string'&&a.findIndex(y=>y&&y.id===x.id)===i);s.name=String(s.name||'SANEK').slice(0,20);
 if(!s.dailyStats||s.dailyStats.id!==day())s.dailyStats={id:day(),opens:0,wins:0,ads:0,upgrades:0,claimed:[]};
 if(!s.weekly||s.weekly.id!==week())s.weekly={id:week(),score:0};if(!s.wheel||s.wheel.day!==day())s.wheel={day:day(),used:0,credit:null};if(!s.login||!Number.isFinite(s.login.last)||!Number.isInteger(s.login.streak)||s.login.streak<0||s.login.streak>7)s.login={last:-1,streak:0};for(const k of ['opens','wins','ads','upgrades'])if(!Number.isFinite(s.dailyStats[k])||s.dailyStats[k]<0)s.dailyStats[k]=0;if(!Array.isArray(s.dailyStats.claimed))s.dailyStats.claimed=[];if(!Number.isFinite(s.weekly.score)||s.weekly.score<0)s.weekly.score=0;if(!Number.isInteger(s.wheel.used)||s.wheel.used<0||s.wheel.used>3)s.wheel.used=0;if(typeof s.wheel.credit!=='string')s.wheel.credit=null;return s;}
function readState(){try{const raw=localStorage.getItem(CONFIG.key);if(raw)return normalize(JSON.parse(raw));const old=localStorage.getItem('caseclash.v3');return old?normalize({...JSON.parse(old),version:4}):fresh();}catch{return fresh();}}
state=readState();
function netWorth(s=state){return s.inv.reduce((a,x)=>a+skins[x.skin][3],0);}
function level(s=state){return 1+Math.floor(s.xp/200);}
function premium(s=state){return s.premiumUntil>Date.now();}
function xp(s,n){s.xp+=n;s.passXP+=n;}
function progress(s,key,n=1){s[key]=(s[key]||0)+n;s.dailyStats[key]=(s.dailyStats[key]||0)+n;}
function grant(s,r){if(r.coins)s.coins+=r.coins;if(r.gems)s.gems+=r.gems;if(r.xp)xp(s,r.xp);if(Number.isInteger(r.case))s.caseTokens.push({id:uid(),case:r.case});if(Number.isInteger(r.skin))s.inv.push(item(r.skin));if(r.cosmetic&&!s.cosmetics.includes(r.cosmetic))s.cosmetics.push(r.cosmetic);}
function unlock(s){const tests={'FIRST DROP':s.opens>=1,'100 CASES':s.opens>=100,'LUCKY ONE':s.inv.some(x=>CONFIG.rarity[x.skin]==='LEGENDARY'),'BATTLE MASTER':s.wins>=10,'COLLECTOR':s.inv.length>=20,'TOP 100':rank('GLOBAL',s)<=100};for(const [a,ok]of Object.entries(tests))if(ok&&!s.achievements.includes(a)){s.achievements.push(a);s.coins+=25;xp(s,50);}}
async function transact(label,fn){const run=()=>{const s=readState();const value=fn(s);if(value===false){state=s;sync();return false;}unlock(s);s.revision++;s.activity.unshift({label,at:Date.now()});s.activity=s.activity.slice(0,40);try{localStorage.setItem(CONFIG.key,JSON.stringify(s));}catch{toastMsg('Хранилище недоступно. Действие не сохранено.');return false;}state=s;sync();return value===undefined?true:value;};return navigator.locks? navigator.locks.request(CONFIG.key,run):run();}
function save(){unlock(state);state.revision++;try{localStorage.setItem(CONFIG.key,JSON.stringify(state));}catch{toastMsg('Не удалось сохранить прогресс');}sync();}
window.addEventListener('storage',e=>{if(e.key===CONFIG.key&&!busy){state=readState();sync();if(currentPanel)showPanel(currentPanel);}});
function wallet(){return `<div class="sceneWallet"><span>${coin} <b data-coins>${fmt(state.coins)}</b> COINS</span><span>${icon('gem')} <b data-gems>${fmt(state.gems)}</b> GEMS</span><span>LVL ${level()}</span></div>`;}
function sync(){legacySync();$$('[data-coins]').forEach(e=>e.textContent=fmt(state.coins));$$('[data-gems]').forEach(e=>e.textContent=fmt(state.gems));const p=$('.profile');if(p){p.classList.toggle('premiumActive',premium());const small=p.querySelector('small');if(small)small.textContent='LVL '+level();}if($('#dailyTime'))$('#dailyTime').textContent=state.login.last===day()?'Получено сегодня':'Награда дня · CLAIM';}
function scene(title,html,panel){return openModal(title,`<div class="sceneShell">${wallet()}${html}</div>`,panel);}
function rarity(i){return CONFIG.rarity[i];}
function richItem(x,action='detail'){return `<button class="lootCard" style="--rarity:${CONFIG.colors[rarity(x.skin)]}" onclick="${action==='select'?`selectUpgrade('${x.id}')`:`itemDetail('${x.id}')`}"><span class="eyebrow">${rarity(x.skin)}</span>${weapon(x.skin)}<b>${skins[x.skin][0]}</b><span>${skins[x.skin][1]}</span><strong>${fmt(skins[x.skin][3])} NW</strong></button>`;}
function rewardText(r){return [r.coins&&`${r.coins} Coins`,r.gems&&`${r.gems} Gems`,r.xp&&`${r.xp} XP`,Number.isInteger(r.case)&&`${cases[r.case][0]} Case`,Number.isInteger(r.skin)&&skins[r.skin][1],r.cosmetic].filter(Boolean).join(' + ');}
let quantity=1,invFilter='ALL',invSort='NEWEST',upgradeSource=null,upgradeTarget=null;
function openCase(name,price,token=null){if(busy)return;const index=cases.findIndex(x=>x[0]===name);currentCase={name,index:index<0?3:index,price:index<0?299:cases[index][2],token};quantity=token?1:quantity;scene(name+' / OPEN',`<div class="sceneIntro"><span class="eyebrow">CASE COLLECTION</span><h2>${esc(name)}</h2><p>Открытие → рулетка → твой новый предмет</p></div><div class="caseStage">${caseArt(currentCase.index)}</div><div id="caseRolls"></div><div id="result" aria-live="polite"></div><div class="sceneControls"><div class="segmented">${[1,3,5].map(n=>`<button class="btn ${quantity===n?'primary':''}" onclick="setQuantity(${n})" ${token&&n!==1?'disabled':''}>x${n}</button>`).join('')}</div><button id="spinButton" class="btn primary big" onclick="spin()">OPEN · ${token?'FREE CASE':fmt(currentCase.price*quantity)+' COINS'}</button><button class="btn" onclick="runAd('${currentCase.index===0?'case':'coins'}')">${currentCase.index===0?'WATCH AD & OPEN':'WATCH DEMO AD · +25 COINS'}</button><details><summary>VIEW ODDS</summary>${skins.map((s,i)=>`<p>${s[0]} ${s[1]} <b>${CONFIG.drops[i]/100}%</b></p>`).join('')}</details></div>`,'case');}
function setQuantity(n){if(busy||![1,3,5].includes(n))return;quantity=n;openCase(currentCase.name,currentCase.price,currentCase.token);}
async function spin(){if(busy||currentPanel!=='case')return;busy=true;$('#spinButton').disabled=true;const c={...currentCase},n=c.token?1:quantity;const outcome=await transact('Open '+n+' '+c.name,s=>{if(c.token){const ix=s.caseTokens.findIndex(t=>t.id===c.token);if(ix<0)return false;s.caseTokens.splice(ix,1);}else{if(s.coins<c.price*n)return false;s.coins-=c.price*n;}const won=Array.from({length:n},()=>item(weighted(CONFIG.drops)));s.inv.push(...won);progress(s,'opens',n);xp(s,25*n);s.weekly.score+=won.reduce((a,x)=>a+skins[x.skin][3],0);return won;});if(!outcome){busy=false;$('#spinButton').disabled=false;toastMsg('Не хватает Coins или кейс уже использован');return;}
 $('.caseStage').hidden=true;$('#caseRolls').innerHTML=outcome.map((x,k)=>`<div class="roulette"><div class="marker"></div><div class="track" id="track${k}">${Array.from({length:34},(_,i)=>rollCard(i===28?x.skin:weighted(CONFIG.drops))).join('')}</div></div>`).join('');
 requestAnimationFrame(()=>requestAnimationFrame(()=>outcome.forEach((x,k)=>{const t=$('#track'+k),a=t.children[28].getBoundingClientRect(),b=t.parentElement.getBoundingClientRect();t.style.transition=`transform ${2.8+k*.15}s cubic-bezier(.08,.65,.1,1)`;t.style.transform=`translateX(-${a.left+a.width/2-b.left-b.width/2}px)`;})));
 $('.modalBox').scrollTop=0;setTimeout(()=>{busy=false;$('#caseRolls').innerHTML='';$('#result').className='result show reveal rarity-'+rarity(outcome.reduce((a,b)=>skins[a.skin][3]>skins[b.skin][3]?a:b).skin).toLowerCase();$('#result').style.setProperty('--rarity',CONFIG.colors[rarity(outcome.reduce((a,b)=>skins[a.skin][3]>skins[b.skin][3]?a:b).skin)]);$('#result').innerHTML=`<span class="eyebrow">COLLECTION UPDATED · +${25*n} XP</span><h2>${n===1?'YOUR DROP':'YOUR DROPS'}</h2><div class="lootGrid">${outcome.map(x=>richItem(x)).join('')}</div><div class="actions"><button class="btn primary" onclick="showPanel('inventory')">KEEP · INVENTORY</button><button class="btn" onclick="openCase('${c.name}',${c.price})">OPEN AGAIN</button></div>`;$('.sceneControls').hidden=true;},3200+n*150);}
function inventory(){let list=state.inv.filter(x=>invFilter==='ALL'||rarity(x.skin)===invFilter);list.sort(invSort==='VALUE'?(a,b)=>skins[b.skin][3]-skins[a.skin][3]:invSort==='RARITY'?(a,b)=>['COMMON','RARE','EPIC','LEGENDARY'].indexOf(rarity(b.skin))-['COMMON','RARE','EPIC','LEGENDARY'].indexOf(rarity(a.skin)):(a,b)=>b.at-a.at);scene('INVENTORY',`<div class="sceneIntro"><h2>YOUR COLLECTION</h2><p>${state.inv.length} items · Net Worth ${fmt(netWorth())}</p></div><div class="filterBar"><label>RARITY<select onchange="invFilter=this.value;inventory()">${['ALL','COMMON','RARE','EPIC','LEGENDARY'].map(x=>`<option ${x===invFilter?'selected':''}>${x}</option>`).join('')}</select></label><label>SORT<select onchange="invSort=this.value;inventory()">${['VALUE','NEWEST','RARITY'].map(x=>`<option ${x===invSort?'selected':''}>${x}</option>`).join('')}</select></label></div>${state.caseTokens.length?`<h3>FREE CASES · ${state.caseTokens.length}</h3><div class="tokenRow">${state.caseTokens.map(t=>`<button class="btn" onclick="openCase('${cases[t.case][0]}',0,'${t.id}')">${cases[t.case][0]} · OPEN</button>`).join('')}</div>`:''}<div class="lootGrid">${list.map(x=>richItem(x)).join('')||'<p class="empty">Нет предметов для этого фильтра.</p>'}</div><button class="btn primary" onclick="showPanel('cases')">GET MORE ITEMS</button>`,'inventory');}
function itemDetail(id){const x=state.inv.find(x=>x.id===id);if(!x)return inventory();scene(skins[x.skin][1],`<div class="itemReveal" style="--rarity:${CONFIG.colors[rarity(x.skin)]}"><span class="eyebrow">${rarity(x.skin)}</span>${weapon(x.skin)}<h2>${skins[x.skin][0]}</h2><h3>${skins[x.skin][1]}</h3><p>${fmt(skins[x.skin][3])} NET WORTH · ${new Date(x.at).toLocaleDateString('ru-RU')}</p></div><div class="actions"><button class="btn primary" onclick="selectUpgrade('${id}')">USE IN UPGRADE</button><button class="btn" onclick="exchangeItem('${id}')">EXCHANGE · ${sellValue(x.skin)} COINS</button><button class="btn" onclick="inventory()">BACK TO INVENTORY</button></div>`,'item');modalLocation.itemId=id;}

function upgradeChance(source,target){if(!Number.isInteger(source)||!Number.isInteger(target)||!skins[source]||!skins[target]||skins[target][3]<=skins[source][3])return 0;return Math.round(Math.min(CONFIG.upgrade.maxChance,skins[source][3]/skins[target][3]*CONFIG.upgrade.margin)*10000)/10000;}
let upgradePane='mine',upgradeSearch={mine:'',targets:''},upgradeRarity={mine:'ALL',targets:'ALL'},upgradeOrder={mine:'DESC',targets:'ASC'},upgradeOutcome=null;
function selectUpgrade(id){if(busy)return;upgradeSource=id;upgradeOutcome=null;if(!upgradeChance(state.inv.find(x=>x.id===id)?.skin,upgradeTarget))upgradeTarget=null;if(currentPanel==='upgrade')refreshUpgrade();else showUpgrade();}
function selectTarget(i){if(busy)return;const source=state.inv.find(x=>x.id===upgradeSource);if(!source||!upgradeChance(source.skin,i))return;upgradeTarget=i;upgradeOutcome=null;refreshUpgrade();}
function upgradeItemCard(i,title,selected,action){return '<button class="upgradeHeroItem '+(selected?'selected':'')+'" onclick="'+action+'"><span class="eyebrow">'+title+'</span>'+(Number.isInteger(i)?weapon(i)+'<b>'+skins[i][0]+'</b><span>'+skins[i][1]+'</span><small style="color:'+CONFIG.colors[rarity(i)]+'">'+rarity(i)+'</small><strong>'+fmt(skins[i][3])+' NW</strong>':'<span class="itemSlot">'+icon('case')+'</span><b>Выбрать предмет</b><small>Нажми, чтобы открыть список</small>')+'</button>';}
function upgradeArenaHTML(){const source=state.inv.find(x=>x.id===upgradeSource),p=upgradeChance(source?.skin,upgradeTarget);return upgradeItemCard(source?.skin,'MY ITEM',!!source,"switchUpgradePane('mine',true)")+'<div class="upgradeCenter"><div class="probability terminalRing" style="--chance:'+p*100+'%"><strong>'+ (p*100).toFixed(2)+'<small>%</small></strong><span>SUCCESS CHANCE</span></div><button id="upgradeExecute" class="btn primary big" onclick="performUpgrade()" '+(!p?'disabled':'')+'>UPGRADE</button><span class="upgradeMargin">Value ratio × '+CONFIG.upgrade.margin+' · max '+CONFIG.upgrade.maxChance*100+'%</span></div>'+upgradeItemCard(upgradeTarget,'TARGET ITEM',upgradeTarget!==null,"switchUpgradePane('targets',true)");}
function upgradeToolbar(pane){return '<div class="upgradeTools"><input aria-label="'+(pane==='mine'?'Search my items':'Search target items')+'" type="search" placeholder="Search name / finish" value="'+esc(upgradeSearch[pane])+'" oninput="upgradeSearch[\''+pane+'\']=this.value;renderUpgradeLists()"><div><select aria-label="'+pane+' rarity" onchange="upgradeRarity[\''+pane+'\']=this.value;renderUpgradeLists()">'+['ALL','COMMON','RARE','EPIC','LEGENDARY'].map(r=>'<option '+(upgradeRarity[pane]===r?'selected':'')+'>'+r+'</option>').join('')+'</select><select aria-label="'+pane+' sort" onchange="upgradeOrder[\''+pane+'\']=this.value;renderUpgradeLists()"><option value="ASC" '+(upgradeOrder[pane]==='ASC'?'selected':'')+'>Value ↑</option><option value="DESC" '+(upgradeOrder[pane]==='DESC'?'selected':'')+'>Value ↓</option></select></div></div>';}
function showUpgrade(){if(busy)return;state=readState();if(!state.inv.some(x=>x.id===upgradeSource))upgradeSource=null;if(upgradeSource&&!upgradeChance(state.inv.find(x=>x.id===upgradeSource).skin,upgradeTarget))upgradeTarget=null;scene('UPGRADE', '<div class="upgradeTerminal"><div class="terminalHeading"><span class="eyebrow">CASE CLASH / UPGRADE LAB</span><h2>THE NEXT LEVEL</h2><p>Выбери свой предмет и цель. Предмет расходуется при любой попытке.</p></div><div id="upgradeOutcome" aria-live="polite"></div><div id="upgradeMain" class="upgradeMain">'+upgradeArenaHTML()+'</div><div class="upgradeTabs" role="tablist" aria-label="Upgrade item selectors"><button class="btn" role="tab" id="mineTab" aria-controls="minePanel" onclick="switchUpgradePane(\'mine\')">MY ITEMS</button><button class="btn" role="tab" id="targetsTab" aria-controls="targetsPanel" onclick="switchUpgradePane(\'targets\')">TARGETS</button></div><div class="upgradeSelectors">'+['mine','targets'].map(pane=>'<section id="'+pane+'Panel" class="upgradeSelector" data-pane="'+pane+'"><div class="selectorHeading"><h3>'+(pane==='mine'?'MY INVENTORY':'TARGET ITEMS')+'</h3><small>'+(pane==='mine'?fmt(netWorth())+' NW total':'Higher-value collection items')+'</small></div>'+upgradeToolbar(pane)+'<div class="upgradeList" id="'+pane+'Items"></div></section>').join('')+'</div></div>', 'upgrade');renderUpgradeLists();switchUpgradePane(upgradePane);renderUpgradeOutcome();}
function renderUpgradeLists(){if(currentPanel!=='upgrade')return;const source=state.inv.find(x=>x.id===upgradeSource);for(const pane of ['mine','targets']){let items=pane==='mine'?state.inv.slice():skins.map((s,i)=>({id:'target-'+i,skin:i})).filter(x=>!source||upgradeChance(source.skin,x.skin)>0);const query=upgradeSearch[pane].trim().toLowerCase();items=items.filter(x=>(upgradeRarity[pane]==='ALL'||rarity(x.skin)===upgradeRarity[pane])&&(!query||(skins[x.skin][0]+' '+skins[x.skin][1]).toLowerCase().includes(query))).sort((a,b)=>(skins[a.skin][3]-skins[b.skin][3])*(upgradeOrder[pane]==='ASC'?1:-1));$('#'+pane+'Items').innerHTML=items.map(x=>'<button class="upgradePick '+((pane==='mine'?upgradeSource===x.id:upgradeTarget===x.skin)?'selected':'')+'" aria-pressed="'+(pane==='mine'?upgradeSource===x.id:upgradeTarget===x.skin)+'" style="--rarity:'+CONFIG.colors[rarity(x.skin)]+'" onclick="'+(pane==='mine'?"selectUpgrade('"+x.id+"')":'selectTarget('+x.skin+')')+'" '+(pane==='targets'&&!source?'disabled':'')+'>'+weapon(x.skin)+'<b>'+skins[x.skin][0]+'</b><span>'+skins[x.skin][1]+'</span><small>'+rarity(x.skin)+'</small><strong>'+fmt(skins[x.skin][3])+' NW</strong></button>').join('')||'<p class="empty">'+(pane==='mine'&&!state.inv.length?'В инвентаре пока пусто. Открой кейс, чтобы получить предмет.':'Нет предметов по выбранным условиям.')+'</p>';if(pane==='targets'&&!source)$('#targetsItems').insertAdjacentHTML('afterbegin','<p class="selectorHint">Сначала выбери MY ITEM.</p>');}}
function switchUpgradePane(pane,scroll=false){if(busy||!['mine','targets'].includes(pane))return;upgradePane=pane;for(const p of ['mine','targets']){$('#'+p+'Panel')?.classList.toggle('active',p===pane);$('#'+p+'Tab')?.setAttribute('aria-selected',String(p===pane));$('#'+p+'Tab')?.classList.toggle('primary',p===pane);}if(scroll)$('#'+pane+'Panel')?.scrollIntoView({block:'start',behavior:'smooth'});}
function refreshUpgrade(){if(busy)return;$('#upgradeMain').innerHTML=upgradeArenaHTML();renderUpgradeLists();renderUpgradeOutcome();}
function renderUpgradeOutcome(){const box=$('#upgradeOutcome');if(!box)return;if(!upgradeOutcome){box.innerHTML='';return;}const r=upgradeOutcome;box.innerHTML='<div class="upgradeVerdict '+(r.ok?'upgradeWon':'upgradeLost')+'"><span class="eyebrow">'+(r.ok?'UPGRADE SUCCESS':'UPGRADE FAILED')+'</span><h3>'+(r.ok?skins[r.target][0]+' · '+skins[r.target][1]:'Предмет израсходован')+'</h3><p>'+(r.ok?'Новая цель добавлена в Inventory.':'Цель не начислена. Можно выбрать другой предмет.')+' Шанс '+(r.p*100).toFixed(2)+'% · +40 XP</p><button class="btn" onclick="inventory()">INVENTORY</button><button class="btn" onclick="upgradeOutcome=null;renderUpgradeOutcome()">CONTINUE</button></div>';}
async function performUpgrade(){if(busy||currentPanel!=='upgrade')return;const source=upgradeSource,target=upgradeTarget;if(!upgradeChance(state.inv.find(x=>x.id===source)?.skin,target))return;busy=true;$('#upgradeExecute').disabled=true;$('.upgradeTerminal').classList.add('isRunning');$('.upgradeSelectors').inert=true;const result=await transact('Upgrade',s=>{const ix=s.inv.findIndex(x=>x.id===source);if(ix<0)return false;const original=s.inv[ix],p=upgradeChance(original.skin,target);if(!p)return false;const ok=randomUnit()<p;s.inv.splice(ix,1);if(ok){s.inv.push(item(target));s.upgradeWins++;s.weekly.score+=skins[target][3]-skins[original.skin][3];}progress(s,'upgrades');xp(s,40);return {ok,p,target,source:original.skin};});if(!result){busy=false;showUpgrade();return;}$('.terminalRing').classList.add('rolling');setTimeout(()=>{busy=false;upgradeSource=null;upgradeOutcome=result;showUpgrade();$('#upgradeOutcome').scrollIntoView({block:'start',behavior:'smooth'});},CONFIG.upgrade.animationMs);}

async function exchangeItem(id){if(busy)return;await transact('Exchange item',s=>{const i=s.inv.findIndex(x=>x.id===id);if(i<0)return false;s.coins+=sellValue(s.inv[i].skin);s.inv.splice(i,1);});inventory();}
function showBattle(mode='1x1'){if(busy)return;if(!['1x1','2x2','3x3'].includes(mode))mode='1x1';battleMode=mode;scene('CASE BATTLE',`<div class="sceneIntro"><span class="eyebrow">TEAM ARENA / 3 ROUNDS</span><h2>WIN TOGETHER</h2><p>Ты и demo bots против команды ботов.<br>Победитель определяется суммой всех предметов за 3 раунда.</p></div><div class="battleBanner">${weapon(0)}<b>VS</b>${weapon(1)}</div><div class="segmented">${['1x1','2x2','3x3'].map(m=>`<button class="btn ${m===mode?'primary':''}" onclick="showBattle('${m}')">${m.replace('x','v')}</button>`).join('')}</div>${battleRoster(mode)}<div class="sceneControls"><button id="battleStart" class="btn primary big" onclick="startBattle()">CREATE & PLAY · ${CONFIG.battleCost} COINS</button><p>Победа: 98 Coins и твои 3 предмета. Ничья: возврат входа.</p></div><div id="battleLog"></div><h3>RECENT BATTLES</h3><div id="battleHistory">${battleHistory()}</div>`,'battle');}
async function startBattle(){if(busy||currentPanel!=='battle')return;busy=true;$('#battleStart').disabled=true;const mode=battleMode,n=parseInt(mode);const result=await transact('Battle '+mode,s=>{if(s.coins<CONFIG.battleCost)return false;s.coins-=CONFIG.battleCost;const rounds=Array.from({length:CONFIG.rounds},()=>({left:Array.from({length:n},()=>weighted(CONFIG.drops)),right:Array.from({length:n},()=>weighted(CONFIG.drops))}));const a=rounds.reduce((t,r)=>t+r.left.reduce((v,i)=>v+skins[i][3],0),0),b=rounds.reduce((t,r)=>t+r.right.reduce((v,i)=>v+skins[i][3],0),0),won=a>b,tie=a===b;if(won){progress(s,'wins');s.coins+=98;s.inv.push(...rounds.map(r=>item(r.left[0])));s.weekly.score+=rounds.reduce((v,r)=>v+skins[r.left[0]][3],0);}if(tie)s.coins+=CONFIG.battleCost;xp(s,60);const entry={mode,a,b,won,tie,at:Date.now(),rounds};s.battles.push(entry);return entry;});if(!result){busy=false;$('#battleStart').disabled=false;toastMsg('Нужно 49 Coins');return;}let round=0;const log=$('#battleLog');function step(){round++;log.innerHTML=`<h2>ROUND ${round} / 3</h2><p class="runningScore">${fmt(result.rounds.slice(0,round).reduce((t,r)=>t+r.left.reduce((v,i)=>v+skins[i][3],0),0))} : ${fmt(result.rounds.slice(0,round).reduce((t,r)=>t+r.right.reduce((v,i)=>v+skins[i][3],0),0))}</p>${result.rounds.slice(0,round).map((r,i)=>`<div class="round"><span>ROUND ${i+1}</span><div class="battleSlots"><div><h3>${esc(state.name)}${n>1?' + TEAM':''}</h3>${r.left.map((s,j)=>`<div class="battleDrop">${playerChip(j===0?state.name:BOT_NAMES[j-1],j===0?'you':'bot'+j)}${weapon(s)}<span>${skins[s][1]} · ${fmt(skins[s][3])}</span></div>`).join('')}</div><div><h3>DEMO BOTS</h3>${r.right.map((s,j)=>`<div class="battleDrop">${playerChip(BOT_NAMES[j+4],'opponent'+j)}${weapon(s)}<span>${skins[s][1]} · ${fmt(skins[s][3])}</span></div>`).join('')}</div></div></div>`).join('')}`;if(round<3)setTimeout(step,900);else{busy=false;log.insertAdjacentHTML('beforeend',`<div class="battleVerdict"><span class="eyebrow">FINAL SCORE</span><h2>${fmt(result.a)} : ${fmt(result.b)}</h2><h3>${result.tie?'DRAW':result.won?'YOUR TEAM WINS':'BOT TEAM WINS'}</h3><p>${result.won?'+98 Coins · 3 предмета в Inventory':result.tie?'49 Coins возвращены':'Твои предметы в Inventory сохранены'} · +60 XP</p><button class="btn primary" onclick="showBattle('${mode}')">PLAY AGAIN</button><button class="btn" onclick="inventory()">INVENTORY</button></div>`);$('#battleHistory').innerHTML=battleHistory();}}log.scrollIntoView({block:'start',behavior:'smooth'});step();}
// Providers expose receipts; all grants go through the same atomic transaction.

function product(id){return [...CONFIG.gems,...CONFIG.premium,CONFIG.pass].find(x=>x.id===id);}
function storePage(){scene('STORE',`<div class="sceneIntro"><span class="eyebrow">MAKE IT YOURS</span><h2>THE GEM VAULT</h2><p>Demo checkout · реальные деньги не списываются.</p></div><div class="storeGrid">${CONFIG.gems.map(g=>`<article class="storePack ${g.label?'featured':''}"><span class="eyebrow">${g.label||'GEMS PACK'}</span><div class="gemEmblem">${icon('gem')}</div><h2>${fmt(g.gems)}</h2><p>GEMS</p><button class="btn primary" onclick="buy('${g.id}')">BUY · ${fmt(g.price)} ₽</button></article>`).join('')}</div><div class="actions"><button class="btn" onclick="convertGems()" ${state.gems<100?'disabled':''}>100 GEMS → 100 COINS</button><button class="btn" onclick="addDemoCoins()">+1 000 TEST COINS</button><button class="btn" onclick="showPanel('premium')">PREMIUM</button><button class="btn" onclick="showPanel('pass')">BATTLE PASS</button></div><p>Цифровые предметы остаются в игре. Вывода и денежных ставок нет.</p><h3>PAYMENT HISTORY</h3>${state.payments.slice(-8).reverse().map(p=>`<div class="ledgerRow"><span>${esc(product(p.productId)?.name||product(p.productId)?.gems+' Gems')}</span><b>${p.status.toUpperCase()}</b>${p.status==='pending'?`<button class="btn" onclick="checkout('${p.id}')">CONTINUE</button>`:''}</div>`).join('')||'<p>Пока нет покупок.</p>'}`,'shop');}
async function buy(id){if(busy)return;if(id==='pass'&&state.passOwned)return;busy=true;const p=await paymentProvider.createPayment(id);busy=false;if(p)checkout(p.id);}
function checkout(id){const p=state.payments.find(x=>x.id===id);if(!p)return storePage();const g=product(p.productId);scene('DEMO CHECKOUT',`<div class="checkout"><span class="eyebrow">SIMULATED PAYMENT</span><h2>${g.gems?g.gems+' GEMS':g.name}</h2><h3>${fmt(g.price)} ₽ · demo</h3><p>Выбери исход тестовой оплаты.<br>Начисление произойдёт только после SUCCESS.</p><div class="actions"><button class="btn primary" onclick="paymentResult('${id}','success')" ${p.status!=='pending'?'disabled':''}>SUCCESS</button><button class="btn" onclick="paymentResult('${id}','failure')" ${p.status!=='pending'?'disabled':''}>FAILURE</button><button class="btn" onclick="paymentResult('${id}','cancel')" ${p.status!=='pending'?'disabled':''}>CANCEL</button></div></div>`,'payment');modalLocation.paymentId=id;}
async function paymentResult(id,status){if(busy)return;busy=true;const p=await paymentProvider.complete(id,status);const verified=p?await paymentProvider.verifyPayment(id):null;busy=false;if(p&&status==='success'&&!verified?.verified){toastMsg('Ожидаем подтверждение оплаты');return checkout(id);}if(!p){toastMsg('Платёж уже обработан');return storePage();}scene('PAYMENT '+status.toUpperCase(),`<div class="checkout"><h2>${status.toUpperCase()}</h2><p>${status==='success'?'Покупка начислена и сохранена.':'Ничего не начислено. Баланс не изменился.'}</p><button class="btn primary" onclick="storePage()">BACK TO STORE</button><button class="btn" onclick="showPanel('profile')">PROFILE</button></div>`,'result');}
function premiumPage(){scene('PREMIUM',`<div class="premiumHero">${icon('crown')}<span class="eyebrow">CASE CLASH / MEMBERS CLUB</span><h2>${premium()?'WELCOME TO PREMIUM':'OWN YOUR STYLE'}</h2><p>${premium()?'Активен до '+new Date(state.premiumUntil).toLocaleDateString('ru-RU'):'Золотой badge, Premium frame и настройка профиля.'}</p></div><div class="grid2">${CONFIG.premium.map(p=>`<article class="storePack"><h2>${p.name}</h2><p>${p.days} дней · без автоматического продления</p><button class="btn primary" onclick="buy('${p.id}')">PURCHASE · ${fmt(p.price)} ₽</button></article>`).join('')}</div><button class="btn" onclick="showPanel('profile')">CUSTOMIZE PROFILE</button><p>Demo purchase · платёжный API не подключён.</p>`,'premium');}
async function addDemoCoins(){if(busy)return;await transact('Test coins',s=>{s.coins+=1000;});storePage();}
async function convertGems(){if(busy)return;await transact('Convert Gems',s=>{if(s.gems<100)return false;s.gems-=100;s.coins+=100;});storePage();}
function wheelPage(){state=readState();scene('SPIN & WIN',`<div class="sceneIntro"><span class="eyebrow">ONE SPIN. ANYTHING CAN HAPPEN.</span><h2>SPIN & WIN</h2><p>${state.wheel.used} / 3 rewarded spins сегодня · сброс 00:00 UTC</p></div><div class="wheelWrap"><div class="wheelPointer"></div><div class="prizeWheel" id="prizeWheel">${CONFIG.wheel.map((r,i)=>`<span style="--angle:${i*45+22.5}deg">${r.name}</span>`).join('')}</div><div class="wheelHub">${icon('crown')}</div></div><div id="wheelResult" aria-live="polite"></div><div class="sceneControls"><button class="btn primary big" onclick="${state.wheel.credit?'spinWheel()':'watchWheelAd()'}" ${state.wheel.used>=3&&!state.wheel.credit?'disabled':''}>${state.wheel.credit?'SPIN':'WATCH AD'}</button><details><summary>VIEW ODDS</summary><p>Секторы одинакового размера для оформления. Вероятности различаются и указаны ниже.</p>${CONFIG.wheel.map(r=>`<div class="ledgerRow"><span>${r.name}</span><b>${r.weight/100}%</b></div>`).join('')}</details></div>`,'wheel');}
async function watchWheelAd(){return runAd('wheel');}
async function rewardAd(){return runAd('coins');}
async function runAd(placement){if(busy||!['wheel','coins','case'].includes(placement))return;const returnCase=currentPanel==='case'?{...currentCase}:null;if(placement==='wheel'&&(state.wheel.used>=3||state.wheel.credit))return wheelPage();scene('DEMO REWARDED AD',`<div class="adStage">${icon('play')}<h2>CASE CLASH</h2><p>DEMO AD · рекламная сеть не подключена</p><progress></progress><p>Просмотр завершается…</p></div>`,'ad');busy=true;const result=await adProvider.watch(placement,receipt=>transact('Rewarded ad',s=>{if(s.adReceipts.includes(receipt.id))return false;if(placement==='wheel'){if(s.wheel.used>=3||s.wheel.credit)return false;s.wheel.credit=receipt.id;s.wheel.used++;}else if(placement==='case'){if(!returnCase)return false;grant(s,{case:returnCase.index});}else s.coins+=25;s.adReceipts.push(receipt.id);progress(s,'ads');xp(s,10);return true;}));busy=false;if(placement==='case'&&result){const token=state.caseTokens.at(-1);openCase(cases[token.case][0],0,token.id);return spin();}if(placement==='wheel')wheelPage();else scene('AD REWARD',`<div class="checkout"><h2>${result?'+25 COINS':'ALREADY CLAIMED'}</h2><p>Просмотр учтён в daily missions.</p>${returnCase?`<button class="btn primary" onclick="openCase('${returnCase.name}',${returnCase.price})">BACK TO CASE</button>`:''}<button class="btn primary" onclick="showPanel('wheel')">SPIN & WIN</button><button class="btn" onclick="showPanel('tasks')">MISSIONS</button></div>`,'result');}
async function spinWheel(){if(busy)return;busy=true;const result=await transact('Wheel spin',s=>{if(!s.wheel.credit)return false;s.wheel.credit=null;const index=weighted(CONFIG.wheel.map(x=>x.weight));grant(s,CONFIG.wheel[index]);xp(s,20);return {index};});if(!result){busy=false;return wheelPage();}const el=$('#prizeWheel');el.style.transform=`rotate(${1800-(result.index*45+22.5)}deg)`;setTimeout(()=>{busy=false;$('#wheelResult').innerHTML=`<div class="reveal"><span class="eyebrow">REWARD SAVED</span><h2>${CONFIG.wheel[result.index].name}</h2><p>${rewardText(CONFIG.wheel[result.index])}</p><button class="btn primary" onclick="wheelPage()">CONTINUE</button><button class="btn" onclick="inventory()">INVENTORY</button></div>`;$('.sceneControls').hidden=true;},3300);}
function passReward(t,p){const free=[{coins:100},{gems:5},{case:1},{cosmetic:'FOUNDERS BADGE'},{coins:200},{case:2},{gems:10},{cosmetic:'SILVER FRAME'},{coins:300},{case:3}];const paid=[{gems:20},{cosmetic:'VIOLET FRAME'},{case:3},{coins:500},{gems:50},{cosmetic:'NEON BADGE'},{case:5},{cosmetic:'GOLD FRAME'},{gems:100},{cosmetic:'LEGEND AURA'}];return (p?paid:free)[t-1];}
function passPage(){const tier=Math.min(10,Math.floor(state.passXP/CONFIG.passXP));scene('BATTLE PASS',`<div class="sceneIntro"><span class="eyebrow">${CONFIG.season} / SEASON 01</span><h2>BUILD YOUR LEGACY</h2><p>Tier ${tier} / 10 · ${state.passXP} Battle Pass XP</p><progress max="1000" value="${state.passXP}"></progress></div>${!state.passOwned?`<button class="btn primary" onclick="buy('pass')">UNLOCK PREMIUM TRACK · ${CONFIG.pass.price} ₽</button>`:'<span class="tag">PREMIUM TRACK ACTIVE</span>'}<div class="passHead"><span>TIER</span><b>FREE</b><b>PREMIUM</b></div>${Array.from({length:10},(_,i)=>i+1).map(t=>`<div class="passRow"><strong>${t}</strong>${[false,true].map(p=>{const key=t+':'+p,claimed=state.passClaims.includes(key),eligible=tier>=t&&(!p||state.passOwned);return `<div><p>${rewardText(passReward(t,p))}</p><button class="btn ${eligible&&!claimed?'primary':''}" onclick="claimPass(${t},${p})" ${!eligible||claimed?'disabled':''}>${claimed?'CLAIMED':eligible?'CLAIM':'LOCKED'}</button></div>`;}).join('')}</div>`).join('')}`,'pass');}
async function claimPass(t,p){if(busy)return;await transact('Claim pass '+t,s=>{const key=t+':'+p;if(!Number.isInteger(t)||t<1||t>10||s.passXP<t*100||(p&&!s.passOwned)||s.passClaims.includes(key))return false;s.passClaims.push(key);grant(s,passReward(t,p));});passPage();}
function loginReward(n){return {coins:n*50,xp:30,...(n===3||n===7?{gems:n===7?20:5}:{}),...(n===7?{case:3,cosmetic:'STREAK BADGE'}:{})};}
function dailyReward(){const claimed=state.login.last===day(),n=claimed?state.login.streak:state.login.last===day()-1?state.login.streak%7+1:1;scene('DAILY LOGIN',`<div class="sceneIntro"><span class="eyebrow">COME BACK. COLLECT MORE.</span><h2>DAY ${n} / 7</h2><p>Новый день начинается в 00:00 UTC. Пропуск дня сбрасывает серию.</p></div><div class="dailyGrid">${Array.from({length:7},(_,i)=>`<div class="panelCard ${(n===i+1?'selected ':'')+(i===6?'daySeven':'')}"><h3>DAY ${i+1}</h3><p>${rewardText(loginReward(i+1))}</p></div>`).join('')}</div><button class="btn primary big" onclick="claimLogin()" ${claimed?'disabled':''}>${claimed?'CLAIMED TODAY':'CLAIM DAILY'}</button>`,'daily');}
async function claimLogin(){if(busy)return;await transact('Daily login',s=>{if(s.login.last===day())return false;const n=s.login.last===day()-1?s.login.streak%7+1:1;s.login={last:day(),streak:n};grant(s,loginReward(n));});dailyReward();}
function taskRows(){return CONFIG.missions.map(t=>{const n=state.dailyStats?.[t.id]||0,claimed=state.dailyStats?.claimed?.includes(t.id);return `<div class="missionRow"><div><b>${t.label}</b><p>${Math.min(n,t.count)} / ${t.count} · ${rewardText(t)}</p></div><button class="btn ${n>=t.count&&!claimed?'primary':''}" onclick="claimTask('${t.id}')" ${n<t.count||claimed?'disabled':''}>${claimed?'CLAIMED':'CLAIM'}</button></div>`;}).join('');}
function missionPage(){scene('DAILY MISSIONS',`<div class="sceneIntro"><h2>PLAY. PROGRESS. CLAIM.</h2><p>Сброс в 00:00 UTC · XP также повышает Battle Pass.</p></div>${taskRows()}<div class="actions"><button class="btn" onclick="rewardAd()">WATCH DEMO AD</button><button class="btn" onclick="showPanel('pass')">BATTLE PASS</button></div>`,'tasks');}
async function claimTask(id){if(busy)return;await transact('Mission '+id,s=>{const t=CONFIG.missions.find(t=>t.id===id);if(!t||s.dailyStats[id]<t.count||s.dailyStats.claimed.includes(id))return false;s.dailyStats.claimed.push(id);grant(s,t);});missionPage();}
const BOT_NAMES=['NOVA','GHOST','VIOLET','RAVEN','KIRA','SPECTRE','ONYX','FROST','MIKA','BLAZE','ECHO','NIK','SAINT','ACE','LUNA','WOLF','ZERO','IVY','REAPER','FLUX'];
function leaderboard(tab='GLOBAL',s=state){const bots=Array.from({length:100},(_,i)=>({id:'bot'+i,level:3+Math.floor((100-i)*.7),name:BOT_NAMES[i%20]+(i<20?'':['_','.', ''][i%3]+(11+i)),GLOBAL:1500+Math.floor((100-i)**2*83.7),WEEKLY:Math.floor((100-i)**1.7*13+(i*127)%7000),WINS:Math.floor((100-i)*2.3+(i*17)%49),COLLECTION:Math.floor((100-i)*3.1+(i*7)%29)}));bots.push({id:'you',level:level(s),name:s.name,GLOBAL:netWorth(s),WEEKLY:s.weekly.score,WINS:s.wins,COLLECTION:s.inv.length});return bots.sort((a,b)=>b[tab]-a[tab]||a.id.localeCompare(b.id));}
function rank(tab='GLOBAL',s=state){return leaderboard(tab,s).findIndex(x=>x.id==='you')+1;}
let leaderTab='GLOBAL';
function leaderboardPage(tab=leaderTab){leaderTab=tab;const rows=leaderboard(tab),pos=rank(tab),units={GLOBAL:'NET WORTH',WEEKLY:'EARNED NW',WINS:'WINS',COLLECTION:'ITEMS'};scene('TOP 100',`<div class="sceneIntro"><span class="eyebrow">THE COLLECTORS CLUB</span><h2>HALL OF FAME</h2><p>100 demo users + ты. Net Worth = стоимость коллекции.<br>Купленный баланс не добавляет очки рейтинга.</p></div><div class="segmented">${['GLOBAL','WEEKLY','WINS','COLLECTION'].map(t=>`<button class="btn ${t===tab?'primary':''}" onclick="leaderboardPage('${t}')">${t}</button>`).join('')}</div><div class="podium">${[1,0,2].map(i=>`<div class="place place${i+1}">${icon(i===0?'crown':'top')}<span>#${i+1}</span>${playerChip(rows[i].name,rows[i].id)}<small>LVL ${rows[i].level}</small><strong>${fmt(rows[i][tab])}</strong><small>${units[tab]}</small></div>`).join('')}</div><div class="myRank"><b>#${pos} · ${esc(state.name)} · YOU</b><strong>${fmt(rows[pos-1][tab])} ${units[tab]}</strong></div><p>Weekly status: TOP 1 crown effect · TOP 3 frames · TOP 10 badge. Статус обновляется с текущим weekly rank.</p><div class="rankingList">${rows.slice(3,100).map((r,i)=>`<div class="rankRow ${r.id==='you'?'selected':''}"><span>#${i+4}</span><div>${playerChip(r.name,r.id)}<small>LVL ${r.level}${r.id==='you'?' · YOU':''}</small></div><strong>${fmt(r[tab])}</strong></div>`).join('')}</div>`,'top');}
function profilePage(){const rare=state.inv.slice().sort((a,b)=>['COMMON','RARE','EPIC','LEGENDARY'].indexOf(rarity(b.skin))-['COMMON','RARE','EPIC','LEGENDARY'].indexOf(rarity(a.skin))||skins[b.skin][3]-skins[a.skin][3])[0],weeklyRank=rank('WEEKLY'),frames=['default',...(premium()?['PREMIUM FRAME']:[]),...state.cosmetics.filter(x=>/FRAME/.test(x)),...(weeklyRank<=3?['WEEKLY FRAME']:[])];const actual=frames.includes(state.frame)?state.frame:'default';scene('PROFILE',`<div class="profileHero ${premium()?'premiumActive':''}"><div class="avatarBig ${actual!=='default'?'framed':''} ${weeklyRank===1?'crowned':''}">${esc(state.name[0])}</div><h2>${esc(state.name)}</h2><span class="tag">LEVEL ${level()}</span>${premium()?'<span class="tag">PREMIUM</span>':''}${weeklyRank<=10?'<span class="tag">WEEKLY TOP 10</span>':''}<p>${state.xp} XP · ${200-state.xp%200} XP to next level</p><progress value="${state.xp%200}" max="200"></progress></div><div class="statsGrid">${[['NET WORTH',fmt(netWorth())],['CASES OPENED',state.opens],['BATTLE WINS',state.wins],['UPGRADE WINS',state.upgradeWins],['COLLECTION',state.inv.length],['GLOBAL RANK','#'+rank()]].map(([k,v])=>`<div><strong>${v}</strong><span>${k}</span></div>`).join('')}</div>${rare?`<h3>RAREST / MOST VALUABLE</h3>${richItem(rare)}`:''}<h3>ACHIEVEMENTS</h3><p>Каждое достижение: +25 Coins и +50 XP, автоматически при открытии.</p><div class="badgeGrid">${['FIRST DROP','100 CASES','LUCKY ONE','BATTLE MASTER','COLLECTOR','TOP 100'].map(a=>`<div class="badge ${state.achievements.includes(a)?'unlocked':''}">${icon('top')}<b>${a}</b><small>${state.achievements.includes(a)?'UNLOCKED':'LOCKED'}</small></div>`).join('')}</div><h3>CUSTOMIZATION</h3><label class="field">NICKNAME<input id="nameInput" maxlength="20" value="${esc(state.name)}"></label><button class="btn primary" onclick="saveName()">SAVE NAME</button><label class="field">FRAME<select onchange="equipFrame(this.value)">${frames.map(f=>`<option ${actual===f?'selected':''}>${f}</option>`).join('')}</select></label><p>${state.cosmetics.map(esc).join(' · ')||'Разблокируй cosmetics в Battle Pass.'}</p><div class="actions"><button class="btn" onclick="showPanel('menu')">PLAY HUB</button><button class="btn" onclick="premiumPage()">PREMIUM</button><button class="btn" onclick="showPanel('pass')">BATTLE PASS</button><button class="btn" onclick="resetPage()">RESET DEMO DATA</button></div>`,'profile');}
async function saveName(){const name=$('#nameInput').value.trim().slice(0,20);if(!name)return toastMsg('Введи имя');await transact('Profile name',s=>{s.name=name;});profilePage();}
async function equipFrame(f){await transact('Profile frame',s=>{if(f==='default'||(f==='PREMIUM FRAME'&&premium(s))||s.cosmetics.includes(f)||(f==='WEEKLY FRAME'&&rank('WEEKLY',s)<=3))s.frame=f;});profilePage();}
function resetPage(){scene('RESET DEMO DATA',`<div class="checkout"><h2>START FRESH?</h2><p>Будут сброшены предметы, награды, платежи и прогресс этой демоверсии на этом устройстве.</p><button class="btn primary" onclick="resetDemo()">CONFIRM RESET</button><button class="btn" onclick="profilePage()">CANCEL</button></div>`,'reset');}
async function resetDemo(){if(busy)return;const reset=()=>{localStorage.removeItem('caseclash.v3');state=fresh();localStorage.setItem(CONFIG.key,JSON.stringify(state));};if(navigator.locks)await navigator.locks.request(CONFIG.key,reset);else reset();quantity=1;upgradeSource=null;upgradeTarget=null;upgradePane='mine';upgradeSearch={mine:'',targets:''};upgradeRarity={mine:'ALL',targets:'ALL'};upgradeOrder={mine:'DESC',targets:'ASC'};upgradeOutcome=null;invFilter='ALL';invSort='NEWEST';sheetHistory=[];modalLocation=null;closeModal();sync();toastMsg('Demo reset · 1 000 Coins · 0 Gems');}
function showPanel(type){if(busy)return toastMsg('Дождись завершения действия');state=readState();const routes={inventory,upgrade:showUpgrade,battle:()=>showBattle('1x1'),shop:storePage,premium:premiumPage,pass:passPage,wheel:wheelPage,top:()=>leaderboardPage(),tasks:missionPage,profile:profilePage,daily:dailyReward};if(routes[type])return routes[type]();if(type==='menu')return scene('PLAY / COLLECT / PROGRESS',`<div class="menuGrid">${[['cases','case','CASES'],['upgrade','upgrade','UPGRADE'],['battle','battle','BATTLE'],['wheel','event','SPIN & WIN'],['inventory','contract','INVENTORY'],['shop','gem','STORE'],['premium','crown','PREMIUM'],['pass','top','BATTLE PASS'],['tasks','tasks','MISSIONS'],['daily','gift','DAILY LOGIN'],['top','top','TOP 100'],['profile','home','PROFILE'],['events','event','EVENT'],['contract','contract','CONTRACT'],['refs','refs','REFERRALS'],['support','support','SUPPORT']].map(([p,i,t])=>`<button class="btn" onclick="showPanel('${p}')">${icon(i)}${t}</button>`).join('')}</div>`,'menu');legacyPanel(type);}
function finishInit(){render();$('.topNav').insertAdjacentHTML('beforeend',`<button onclick="wheelPage()">SPIN & WIN</button>`);$('.caseRow')?.insertAdjacentHTML('afterend','');const row=$('#caseRow');row.insertAdjacentHTML('afterend',`<div class="quickPlay">${[['wheel','SPIN & WIN','event'],['pass','BATTLE PASS','top'],['premium','PREMIUM','crown']].map(([p,t,i])=>`<button onclick="showPanel('${p}')">${icon(i)}<b>${t}</b><span>EXPLORE ›</span></button>`).join('')}</div>`);$$('.drop .value').forEach((e,i)=>e.textContent=fmt(skins[i][3])+' NW');$('.infoCard:nth-child(3) .refbox+p').textContent='Поделись демоверсией с друзьями. Реферальный backend пока не подключён.';$('.profile small')?.replaceChildren(document.createTextNode('LVL '+level()));$$('.stat b').forEach(e=>e.setAttribute('title','Demo community statistic'));sync();}


function playerChip(name,id){const hue=[...id].reduce((a,c)=>a+c.charCodeAt(0),0)%360;return `<span class="playerChip"><span class="playerAvatar" style="--hue:${hue}" aria-label="${esc(name)} avatar">${esc(name.slice(0,2))}</span><b>${esc(name)}</b></span>`;}

function botIdentity(index){const b=leaderboard('GLOBAL').find(x=>x.id==='bot'+index);return '<button class="botIdentity" onclick="botProfile('+index+')">'+playerChip(b.name,b.id)+'<small>LVL '+b.level+' · '+b.WINS+' wins</small></button>';}
function botProfile(index){if(busy)return;const b=leaderboard('GLOBAL').find(x=>x.id==='bot'+index);if(!b)return;scene(b.name+' / DEMO PROFILE','<div class="profileHero">'+playerChip(b.name,b.id)+'<h2>'+esc(b.name)+'</h2><p>DEMO PLAYER · LEVEL '+b.level+'</p></div><div class="statsGrid">'+[['NET WORTH',fmt(b.GLOBAL)],['BATTLE WINS',b.WINS],['COLLECTION',b.COLLECTION],['WEEKLY NW',fmt(b.WEEKLY)]].map(([name,value])=>'<div><strong>'+value+'</strong><span>'+name+'</span></div>').join('')+'</div><button class="btn" onclick="sheetBack()">BACK TO ARENA</button>','bot');}
function battleRoster(mode){const n=parseInt(mode);return '<div class="roster"><div>'+Array.from({length:n},(_,j)=>j===0?'<div>'+playerChip(state.name,'you')+'<small>LVL '+level()+' · '+state.wins+' wins</small></div>':botIdentity(j-1)).join('')+'</div><span>VS</span><div>'+Array.from({length:n},(_,j)=>botIdentity(j+4)).join('')+'</div></div><p class="arenaCases">3 × ELITE CASE · одинаковые шансы для обеих команд</p>';}

function sheetBack(){if(busy)return toastMsg('Дождись завершения действия');const prev=sheetHistory.pop();if(!prev)return closeModal();goingBack=true;if(prev.panel==='case'&&prev.case)openCase(prev.case.name,prev.case.price,prev.case.token);else if(prev.panel==='battle')showBattle(prev.mode);else if(prev.panel==='item'&&prev.itemId)itemDetail(prev.itemId);else if(prev.panel==='payment'&&prev.paymentId)checkout(prev.paymentId);else if(['result','skin','social','ad','reset'].includes(prev.panel))showPanel('profile');else showPanel(prev.panel);}
function setMobileActive(panel){document.body.classList.toggle('immersive',['case','upgrade','battle','wheel','ad','result','payment','item'].includes(panel));document.querySelectorAll('.mobileNav button').forEach(b=>{const active=b.dataset.panel===panel;b.classList.toggle('active',active);if(active)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});}
window.addEventListener('focus',()=>{if(!busy){state=readState();sync();}});

finishInit();
